version: "3.7"

services:
  front-sm:
    image: nigelmann/storeme-webapp:v0.0.1-init-ci-cd-testing.0
    ports:
      - "8080:8080"

  back-sm:
    image: nigelmann/storeme-api:v0.0.1-init-ci-cd-testing.0
    ports:
      - "8090:8080"
