version: "3.7"

services:
  front-sm:
    image: nigelmann/storeme-webapp:latest
    ports:
      - "9080:8080"

  back-sm:
    image: nigelmann/storeme-api:latest
    ports:
      - "9090:8080"

  bd-sm:
    volumes:
        - dev-db-data:/var/lib/postgresql

volumes:
  dev-db-data:
