openapi: "3.0.0"

info:
  title: "storeme cloud API"
  version: "1"

servers:
  - url: http://localhost:8091
    description: catalogue api

paths:
  /example:
    get:
      responses:
        400:
          description: Bad request
components:
  schemas:
    ModelDTO:
      properties:
        id:
          type: integer
          required: false
    LocationDTO:
      properties:
        id:
          type: integer
    ItemDTO:
      properties:
        id:
          type: integer
        modelId:
          type: integer
        movementsId:
          type: array
          items:
            type: integer
    MovementDTO:
      properties:
        id:
          type: integer
        locationId:
          type: integer



