openapi: "3.0.0"

info:
  title: "storeme cloud API"
  version: "1"

servers:
  - url: http://localhost:8091
    description: catalogue api

paths:
  /example:
    get:
      responses:
        400:
          description: Bad request