name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # prepare ssh stuff
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/aws-key-pair
          sudo chmod 600 ~/.ssh/aws-key-pair
          ssh-keyscan $(grep ansible_host infra/an/inventory.yaml | awk '{split($0,a,": "); print a[2]}' | tr -d '"') > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.TEST}}
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'

      # run ansible playbook
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@0.0.5
        with:
          playbook: infra/an/deploy.yaml
          inventory: infra/an/inventory.yaml
          galaxy_file: infra/an/requirements.yaml
          extra_vars: deploy_env=prod
