name: "Development"

on:
  push:
    branches:
      - development

jobs:
  test:
    uses: ./.github/workflows/jobs/test.yml
    secrets: inherit
  
  publish:
    needs: test
    uses: ./.github/workflows/jobs/publish.yml
    secrets: inherit
    with:
      DOCKER_TAG: latest

  deploy:
    needs: publish
    uses: ./.github/workflows/jobs/deploy.yml
    secrets: inherit
    with:
      DEPLOY_ENV: dev
