name: "Master"

on:
  push:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  
  publish:
    needs: test
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      DOCKER_TAG: latest
