name: "Master"

on:
  push:
    branches:
      - "*"
jobs:
  

  test:
    uses: ./test.yml
    secrets: inherit
  
  publish:
    needs: test
    uses: ./publish.yml
    secrets: inherit
    with:
      DOCKER_TAG: latest
