name: "Build & Publish to docker hub"

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    inputs:
      DOCKER_TAG:
        required: true
        type: string

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        run: npm install
        working-directory: './apps/frontend'
      
      - name: build
        run: npm run build
        working-directory: './apps/frontend'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: ./infra/docker/frontend/Dockerfile
          tags: nigelmann/storeme-webapp:${{ inputs.DOCKER_TAG }}
  
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Only for local testing
      - name: Install curl (for nektos/act local CI testing)
        run: apt-get update && apt-get install build-essential curl pkg-config openssl -y
        if: ${{ env.ACT }}
      - name: Download Maven
        run: |
          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
          apt-get update
          apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
        if: ${{ env.ACT }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          # jdk version
          java-version: '19'
          # Note, the adopt here is because I need to use this, you can change to other distributions according to your situation
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        # maven build
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml
        working-directory: './apps/backend'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./infra/docker/backend/Dockerfile
          tags: nigelmann/storeme-api:${{ inputs.DOCKER_TAG }}
